services:
  db:
    image: dgraph/standalone:master
  app: 
    image: nodecode
    ports: 
      - 8080
      - 5173:5173
    command:
      - /bin/sh
      - -c
      - |
        git clone https://github.com/yellowmachine/ika-example-dgraph.git .
        code-server --host 0.0.0.0 /project